
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HPaned hpaned1;

	private global::Gtk.NodeView nvServices;

	private global::Gtk.NodeView nvClients;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("mDNS Browser");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("mDNSBrowser.avahi.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 215;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.nvServices = new global::Gtk.NodeView ();
		this.nvServices.CanFocus = true;
		this.nvServices.Name = "nvServices";
		this.nvServices.EnableSearch = false;
		this.nvServices.HeadersVisible = false;
		this.hpaned1.Add (this.nvServices);
		global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.nvServices]));
		w1.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.nvClients = new global::Gtk.NodeView ();
		this.nvClients.CanFocus = true;
		this.nvClients.Name = "nvClients";
		this.hpaned1.Add (this.nvClients);
		this.Add (this.hpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 728;
		this.DefaultHeight = 532;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
